name: Soteria Pro Audit
     # update to match your branch names and requirements
on:
  push:
    branches: main
  pull_request:
    branches: "*"
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2
      - name: Soteria Pro Audit
        continue-on-error: true    # set to true if you don't want to fail jobs
        uses: soteria-bc/pro-action@v1
        with:
          soteria-token: ${{ secrets.SOTERIA_TOKEN }}
